### ISSUE TITLE
better description line

### ISSUE THREAD

**Issue by bjarthur** [JuliaStats/DimensionalityReduction.jl#20]
the julia package listing currently only provides the package name and description, which for many packages, including DimensionalityReduction ("Methods for dimensionality reduction"), are redundant. would it make sense to change that to read "PCA, ICA, etc." or something more, well, descriptive?  i searched and searched, didn't find PCA or ICA, and only learned of your hard work here after posting a question asking where they were.

**Comment by oxinabox** [comment]
I suggest adding [Depricated] to the description line.

**Comment by ararslan** [comment]
I've modified the description line to reflect that the package is deprecated in favor of another.
