### ISSUE TITLE
Error with version from METADATA.jl

### ISSUE THREAD

**Issue by AlexanderFabisch** [JuliaStats/DimensionalityReduction.jl#4]
Hi John,

with the version from the standard installation (`Pkg.add("DimensionalityRediction")`) I get the following error:

```
ERROR: julia_pkgdir not defined
 in include at boot.jl:238
at /home/afabisch/.julia/DimensionalityReduction/src/DimensionalityReduction.jl:5
at /home/afabisch/Projekte/6473507/VisualizeMNIST.jl:5
```

With the latest version from the repository I don't have this problem.

**Comment by johnmyleswhite** [comment]
I'll update METADATA in a second. Thanks for catching this.

**Comment by johnmyleswhite** [comment]
Fixed now.
