### ISSUE TITLE
Plan for v0.2.0

### ISSUE THREAD

**Issue by lindahua** [JuliaStats/DimensionalityReduction.jl#8]
This package is an important foundation for our efforts towards a machine learning ecosystem. I plan to spend some time to work on this package recently.

Here is a tentative plan:
- [ ] Remove dependence on DataFrames
  
  Particularly, this package should provide core dimensionality reduction algorithms that focus on ordinary arrays. Dependence on data frames should be removed. 
- [ ] Consistent interface
  
  To conform with other machine learning packages, this package should use column-major data set format (_i.e._ each column being an observation).
- [ ] Improve PCA
  
  Implement multiple PCA algorithm (e.g. based on covariance, SVD, transposed data, etc), and a high-level `pca` function that selects an appropriate method based on input data.
- [ ] Linear Discriminant Analysis
- [ ] Independent Component Analysis 
  
  It seems that a Fast ICA algorithm has been implemented. But will add testing codes.
- [ ] Canonical Correlation Analysis
- [ ] Factor Analysis & Probabilistic PCA
- [ ] Classic MDS
  
  It is already here. May need some testing.
- [ ] Separate NMF to another package. 
  
  Nonnegative Matrix Factorization in itself is a big field that deserves its own package. I have created a package [NMF.jl](https://github.com/lindahua/NMF.jl) for this purpose, and implemented a more sophisticated framework there.
- [ ] Move manifold embedding functions to a separate package. These are a different family of methods.

These are the basics. I believe we can release v0.1.0 when these are ready. 

cc: @johnmyleswhite

**Comment by johnmyleswhite** [comment]
Need to read this again, but all of it sounds reasonable on a quick read.

**Comment by lindahua** [comment]
I tagged the current version as v0.1.0, and new version developed under the new plan (which probably has breaking changes) will be tagged v0.2.0.

**Comment by ccsv** [comment]
I would say this would need additional features such as 

Varimax rotation

http://en.wikipedia.org/wiki/Varimax_rotation

**Comment by lindahua** [comment]
Most of these have been implemented in [MultivariateStats.jl](https://github.com/JuliaStats/MultivariateStats.jl)
